-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Creato il: Apr 04, 2024 alle 08:06
-- Versione del server: 10.6.16-MariaDB-0ubuntu0.22.04.1
-- Versione PHP: 8.2.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `erpcupon_produzione`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `activities`
--

CREATE TABLE `activities` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `location_id` bigint(20) UNSIGNED NOT NULL,
  `description` longtext DEFAULT NULL,
  `details` longtext DEFAULT NULL,
  `note` longtext DEFAULT NULL,
  `product_value` int(11) DEFAULT NULL,
  `ipratico_category_id` varchar(255) DEFAULT NULL,
  `ipratico_id` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `prenotare` longtext DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dump dei dati per la tabella `activities`
--

INSERT INTO `activities` (`id`, `name`, `location_id`, `description`, `details`, `note`, `product_value`, `ipratico_category_id`, `ipratico_id`, `created_at`, `updated_at`, `prenotare`) VALUES
(9, 'Villa Crespi - Menù Degustazione Itinerario per Una persona', 2, 'Questo buono regalo è valido per Menù Degustazione Itinerario destinato a una persona al ristorante tre stelle Michelin dello Chef Antonino Cannavacciuolo.', 'Menù degustazione accompagnato da calice di aperitivo, degustazione vini, minerali e caffetteria.', 'Si accettano prenotazioni esclusivamente per il servizio del pranzo di mercoledì, giovedì e venerdì esclusi i giorni festivi.', 485, NULL, NULL, '2024-03-01 13:15:28', '2024-03-30 10:12:55', 'Per prenotazioni scrivere una mail a ristorante@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(10, 'Villa Crespi - Menù Degustazione Mettici l\'anima per Una persona', 2, 'Questo buono regalo è valido per Menù Degustazione Mettici l\'anima destinato a una persona al ristorante tre stelle Michelin dello Chef Antonino Cannavacciuolo.', 'Menù degustazione accompagnato da calice di aperitivo, degustazione vini, minerali e caffetteria.', 'Si accettano prenotazioni esclusivamente per il servizio del pranzo di mercoledì, giovedì e venerdì esclusi i giorni festivi.', 535, NULL, NULL, '2024-03-20 14:04:17', '2024-03-30 10:13:05', 'Per prenotazioni scrivere una mail a ristorante@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(11, 'Villa Crespi - Esperienza in cucina con la brigata destinato a una persona', 2, 'Questo buono regalo è valido per l\'esperienza di cucina con la brigata dello Chef Antonino Cannavacciuolo, tre stelle Michelin, destinato a una persona.', 'Esperienza nella cucina di Antonino Cannavacciuolo dalle 9:30 alle 11:30 con la sua brigata.', 'Si accettano prenotazioni esclusivamente di mercoledì, giovedì e venerdì esclusi i giorni festivi.', 380, NULL, NULL, '2024-03-21 08:29:46', '2024-03-30 10:13:14', 'Per prenotazioni scrivere una mail a ristorante@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(13, 'Villa Crespi - Io e te, tra benessere e gusto per Due persone', 2, 'Questo buono regalo è valido per l’esperienza in cucina con la brigata di Antonino Cannavacciuolo, tre stelle Michelin, destinato a una persona & un percorso benessere nella Wellness Suite di Villa Crespi destinato alla persona che ti accompagna.', 'Esperienza nella cucina tre stelle Michelin, dalle 9:30 alle 11:30 con la brigata dello Chef Antonino Cannavacciuolo mentre la persona che vi accompagna sarà coccolata da un percorso Benessere.', 'Si accettano prenotazioni esclusivamente per il servizio dal giovedì alla domenica, esclusi i giorni festivi.', 580, NULL, NULL, '2024-03-21 10:16:42', '2024-03-30 10:13:21', 'Per prenotazioni scrivere una mail a ristorante@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(14, 'Villa Crespi – Soggiorno Fuga romantica sul lago no bevande in settimana camera doppia', 2, 'Questo buono regalo è valido per il soggiorno Fuga romantica sul lago di una notte con cena nel ristorante tre stelle Michelin dello Chef Antonino Cannavacciuolo.', '- Una notte in una delle nostre camere doppie\n- Colazione a buffet servita direttamente al ristorante\n- Una cena per due persone con menu degustazione Itinerario (bevande non incluse) presso il ristorante 3 stelle Michelin dello Chef Antonino Cannavacciuolo', 'Il buono regalo è utilizzabile esclusivamente il mercoledì o il giovedì, esclusi i giorni festivi e pre-festivi.', 1359, NULL, NULL, '2024-03-30 09:42:51', '2024-03-30 10:13:30', 'Per prenotazioni scrivere una mail a booking@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(15, 'Villa Crespi – Soggiorno Fuga romantica sul lago con bevande in settimana camera doppia', 2, 'Questo buono regalo è valido per il soggiorno Fuga romantica sul lago di una notte con cena nel ristorante tre stelle Michelin dello Chef Antonino Cannavacciuolo', '- Una notte in una delle nostre camere doppie\n- Colazione a buffet servita direttamente al ristorante\n- Una cena per due persone con menu degustazione Itinerario con calice di aperitivo, degustazione vini, minerali e caffetteria presso il ristorante 3 stelle Michelin dello Chef Antonino Cannavacciuolo', 'Il buono regalo è utilizzabile esclusivamente il mercoledì o il giovedì, esclusi i giorni festivi e pre-festivi.', 1769, NULL, NULL, '2024-03-30 09:44:37', '2024-03-30 10:13:36', 'Per prenotazioni scrivere una mail a booking@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(16, 'Villa Crespi – Soggiorno Fuga romantica sul lago no bevande in settimana Suite', 2, 'Questo buono regalo è valido per il soggiorno Fuga romantica sul lago di una notte con cena nel ristorante tre stelle Michelin dello Chef Antonino Cannavacciuolo.', '- Una notte in una delle nostre Suite\n- Colazione a buffet servita direttamente al ristorante\n- Una cena per due persone con menu degustazione Itinerario (bevande non incluse) presso il ristorante 3 stelle Michelin dello Chef Antonino Cannavacciuolo', 'Il buono regalo è utilizzabile esclusivamente il mercoledì o il giovedì, esclusi i giorni festivi e pre-festivi.', 1869, NULL, NULL, '2024-03-30 09:46:36', '2024-03-30 10:13:47', 'Per prenotazioni scrivere una mail a booking@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(17, 'Villa Crespi – Soggiorno Fuga romantica sul lago con bevande in settimana Suite', 2, 'Questo buono regalo è valido per il soggiorno Fuga romantica sul lago di una notte con cena nel ristorante tre stelle Michelin dello Chef Antonino Cannavacciuolo.', '- Una notte in una delle nostre Suite\n- Colazione a buffet servita direttamente al ristorante\n- Una cena per due persone con menu degustazione Itinerario con calice di aperitivo, degustazione vini, minerali e caffetteria presso il ristorante 3 stelle Michelin dello Chef Antonino Cannavacciuolo', 'Il buono regalo è utilizzabile esclusivamente il mercoledì o il giovedì, esclusi i giorni festivi e pre-festivi.', 2279, NULL, NULL, '2024-03-30 09:47:35', '2024-03-30 10:13:57', 'Per prenotazioni scrivere una mail a booking@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(18, 'Villa Crespi – Soggiorno Gourmet con gusto 1 notte in settimana in camera doppia', 2, 'Questo buono regalo è valido per il soggiorno Gourmet con gusto di una notte in settimana con cena nel ristorante tre stelle Michelin dello Chef Antonino Cannavacciuolo.', '- 1 notte in una delle nostre camere \n- Colazione a buffet servita direttamente al ristorante\n- Una Cena per due persone con menu degustazione Mettici l’anima con calice di aperitivo, abbinamento vini, minerali e caffetteria presso il ristorante 3 stelle Michelin dello Chef Antonino Cannavacciuolo\n- Welcome in camera con bottiglia di spumante, frutta fresca e piccola pasticciera', 'Il buono regalo è utilizzabile esclusivamente il mercoledì o il giovedì, esclusi i giorni festivi e pre-festivi.', 1969, NULL, NULL, '2024-03-30 09:50:49', '2024-03-30 10:14:04', 'Per prenotazioni scrivere una mail a booking@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(19, 'Villa Crespi – Soggiorno Gourmet con gusto 1 notte in settimana in suite', 2, 'Questo buono regalo è valido per il soggiorno Gourmet con gusto di una notte in settimana con cena nel ristorante tre stelle Michelin dello Chef Antonino Cannavacciuolo.', '- 1 notte in una delle nostre Suite\n- Colazione a buffet servita direttamente al ristorante\n- Una Cena per due persone con menu degustazione Mettici l’anima con calice di aperitivo, abbinamento vini, minerali e caffetteria presso il ristorante 3 stelle Michelin dello Chef Antonino Cannavacciuolo\n- Welcome in camera con bottiglia di spumante, frutta fresca e piccola pasticciera', 'Il buono regalo è utilizzabile esclusivamente il mercoledì o il giovedì, esclusi i giorni festivi e pre-festivi.', 2479, NULL, NULL, '2024-03-30 09:52:48', '2024-03-30 10:14:36', 'Per prenotazioni scrivere una mail a booking@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(20, 'Villa Crespi – Soggiorno Gourmet con gusto 2 notti week-end in camera doppia', 2, 'Questo buono regalo è valido per il soggiorno Gourmet con gusto di due notti nel fine settimana con cena nel ristorante tre stelle Michelin dello Chef Antonino Cannavacciuolo.', '- 2 notti in una delle nostre camere doppie\n- Colazione a buffet servita direttamente al ristorante\n- Una Cena per due persone con menù degustazione Mettici l’anima con calice di aperitivo, abbinamento vini, acque minerali e caffetteria presso il ristorante 3 stelle Michelin dello Chef Antonino Cannavacciuolo\n- Champagne rosé afternoon tea, con pasticceria fresca e delizie salate servito al lounge bar', 'Il buono regalo è utilizzabile esclusivamente nel week-end, dal venerdì alla domenica, esclusi i giorni festivi e pre-festivi.', 2999, NULL, NULL, '2024-03-30 09:56:00', '2024-03-30 10:14:45', 'Per prenotazioni scrivere una mail a booking@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(21, 'Villa Crespi – Soggiorno Gourmet con gusto 2 notti week-end in Suite', 2, 'Questo buono regalo è valido per il soggiorno Gourmet con gusto di due notti nel fine settimana con cena nel ristorante tre stelle Michelin dello Chef Antonino Cannavacciuolo.', '- 2 notti in una delle nostre Suite\n- Colazione a buffet servita direttamente al ristorante\n- Una Cena per due persone con menù degustazione Mettici l’anima con calice di aperitivo, abbinamento vini, acque minerali e caffetteria presso il ristorante 3 stelle Michelin dello Chef Antonino Cannavacciuolo\n- Champagne rosé afternoon tea, con pasticceria fresca e delizie salate servito al lounge bar', 'Il buono regalo è utilizzabile esclusivamente nel week-end, dal venerdì alla domenica, esclusi i giorni festivi e pre-festivi.', 3099, NULL, NULL, '2024-03-30 09:56:55', '2024-03-30 10:14:57', 'Per prenotazioni scrivere una mail a booking@villacrespi.it oppure telefonare al 00390322911902, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(22, 'Cannavacciuolo Bistrot Torino – Degustazione I classici per Una persona', 3, 'Questo buono regalo è valido per Menù Degustazione I classici destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo.', 'Menù Degustazione I classici (bevande non incluse)', 'Si accettano prenotazioni esclusivamente per il servizio del pranzo dal mercoledì al venerdì, esclusi i giorni festivi.', 120, NULL, NULL, '2024-03-30 10:19:12', '2024-03-30 10:19:12', 'Per prenotazioni scrivere una mail a torino@cannavacciuolobistrot.it oppure telefonare al 00390118399893, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(23, 'Cannavacciuolo Bistrot Torino – Degustazione I classici con bevande per Una persona', 3, 'Questo buono regalo è valido per Menù Degustazione I classici destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo.', 'Menù Degustazione I classici accompagnato da calice di aperitivo, degustazione vini, minerali e caffetteria.', 'Si accettano prenotazioni esclusivamente per il servizio della cena del martedì, e del pranzo e della cena da mercoledì a venerdì, esclusi i giorni festivi', 205, NULL, NULL, '2024-03-30 10:21:42', '2024-03-30 10:21:42', 'Per prenotazioni scrivere una mail a torino@cannavacciuolobistrot.it oppure telefonare al 00390118399893, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(24, 'Laqua Vineyard – Menu degustazione Prologo per Una persona', 6, 'Questo buono regalo è valido per Menù Degustazione Prologo destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', 'Menù Degustazione Prologo (bevande non incluse)', 'Si accettano esclusivamente prenotazioni per il servizio del pranzo dal mercoledì al venerdì, esclusi i giorni festivi.', 130, NULL, NULL, '2024-03-30 10:24:23', '2024-03-30 10:24:23', 'Per prenotazioni scrivere una mail a vineyard@laquacollection.it oppure telefonare al 00390587346782, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(25, 'Laqua Vineyard – Menu degustazione Prologo con bevande per Una persona', 6, 'Questo buono regalo è valido per Menù Degustazione Prologo destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', 'Menù Degustazione Prologo accompagnato da calice di aperitivo, degustazione vini, minerali e caffetteria.', 'Si accettano esclusivamente prenotazioni per il servizio del pranzo dal mercoledì al venerdì, esclusi i giorni festivi.', 230, NULL, NULL, '2024-03-30 10:26:03', '2024-03-30 10:26:03', 'Per prenotazioni scrivere una mail a vineyard@laquacollection.it oppure telefonare al 00390587346782, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(26, 'Laqua Vineyard – Menu degustazione Interludio per Una persona', 6, 'Questo buono regalo è valido per Menù Degustazione Interludio destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', 'Menù Degustazione Interludio (bevande non incluse)', 'Si accettano esclusivamente prenotazioni per il servizio del pranzo dal mercoledì al venerdì, esclusi i giorni festivi.', 160, NULL, NULL, '2024-03-30 10:27:31', '2024-03-30 10:27:31', 'Per prenotazioni scrivere una mail a vineyard@laquacollection.it oppure telefonare al 00390587346782, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(27, 'Laqua Vineyard – Menu degustazione Interludio con bevande per Una persona', 6, 'Questo buono regalo è valido per Menù Degustazione Interludio destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', 'Menù Degustazione Interludio accompagnato da calice di aperitivo, degustazione vini, minerali e caffetteria.', 'Si accettano esclusivamente prenotazioni per il servizio del pranzo dal mercoledì al venerdì, esclusi i giorni festivi.', 265, NULL, NULL, '2024-03-30 10:29:20', '2024-03-30 10:29:20', 'Per prenotazioni scrivere una mail a vineyard@laquacollection.it oppure telefonare al 00390587346782, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(28, 'Laqua Vineyard – Soggiorno Una notte tra i vigneti toscani in settimana', 6, 'Questo buono regalo è valido per il soggiorno Una notte tra i vigneti toscani di una notte in settimana con cena nel ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', '- 1 notte in Suite Cupido per due persone, dal martedì al giovedì\n- Colazione à la carte servita nella vostra Suite\n- Una cena per due persone con menu degustazione Prologo (bevande non incluse)', 'Il buono regalo è utilizzabile esclusivamente il mercoledì o il giovedì, esclusi i giorni festivi e pre-festivi.', 599, NULL, NULL, '2024-03-30 10:31:34', '2024-03-30 10:34:08', 'Per prenotazioni scrivere una mail a vineyard@laquacollection.it oppure telefonare al 00390587346782, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(29, 'Laqua Vineyard – Soggiorno Un week-end che sa di Toscana', 6, 'Questo buono regalo è valido per il soggiorno Un week-end che sa di Toscana di due notti con cena nel ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', '- 2 notti in Suite Cupido per due persone, dal venerdì alla domenica\n- Colazione à la carte servita nella vostra Suite\n- Una cena per due persone con menu degustazione Prologo con calice di aperitivo, abbinamento vini, minerali e caffetteria', 'Il buono regalo è utilizzabile esclusivamente da venerdì alla domenica, esclusi i giorni festivi e pre-festivi.', 1209, NULL, NULL, '2024-03-30 10:33:54', '2024-03-30 10:33:54', 'Per prenotazioni scrivere una mail a vineyard@laquacollection.it oppure telefonare al 00390587346782, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(30, 'Laqua Countryside – Esperienza dall’orto alla cucina per Una persona', 5, 'Questo buono regalo è valido per l\'esperienza dall\'orto alla cucina destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', '- orario dalle h 10.00 alle h. 11.00\n-  tour guidato nell’orto, dove verranno raccolti i prodotti utili alla realizzazione della ricetta \n\n- Grembiule da cucina realizzato a mano da un piccolo laboratorio artigianale italiano\n- Ricettario \n- Certificato simbolico di partecipazione firmato dallo Chef Antonino Cannavacciuolo\n- al termine della preparazione si avrà un assaggio in abbinamento a un calice di vino scelto dal Sommelier\n- pranzo nel Ristorante Cannavacciuolo Countryside con il menu degustazione Nonna Fiorentina (bevande non incluse)', 'Si accettano prenotazioni dal giovedì al lunedì, esclusi  i giorni festivi.', 269, NULL, NULL, '2024-03-30 12:38:17', '2024-03-30 12:38:17', 'Per prenotazioni scrivere una mail a countryside@laquacollection.it oppure telefonare al 003908119460050, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(31, 'Laqua Countryside – Menù Degustazione Carpe Diem per Una persona', 5, 'Questo buono regalo è valido per Menù Degustazione Carpe Diem destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', 'Menù Degustazione Carpe Diem (bevande non incluse)', 'Si accettano esclusivamente prenotazioni per il servizio del pranzo dal giovedì al lunedì, esclusi i giorni festivi.', 120, NULL, NULL, '2024-03-30 12:46:51', '2024-03-30 12:46:51', 'Per prenotazioni scrivere una mail a countryside@laquacollection.it oppure telefonare al 003908119460050, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(32, 'Laqua Countryside – Menù Degustazione Nonna Fiorentina con bevande per Una persona', 5, 'Questo buono regalo è valido per Menù Degustazione Nonna Fiorentina destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', 'Menù Degustazione Nonna Fiorentina accompagnato da calice di aperitivo, degustazione vini, minerali e caffetteria.', 'Si accettano esclusivamente prenotazioni per il servizio del pranzo dal giovedì al lunedì, esclusi i giorni festivi.', 240, NULL, NULL, '2024-03-30 12:49:44', '2024-03-30 12:52:46', 'Per prenotazioni scrivere una mail a countryside@laquacollection.it oppure telefonare al 003908119460050, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(33, 'Laqua Countryside – Menù Degustazione Nonna Fiorentina per Una persona', 5, 'Questo buono regalo è valido per Menù Degustazione Nonna Fiorentina destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', 'Menù Degustazione Nonna Fiorentina (bevande non incluse)', 'Si accettano esclusivamente prenotazioni per il servizio del pranzo dal giovedì al lunedì, esclusi i giorni festivi.', 140, NULL, NULL, '2024-03-30 12:50:49', '2024-03-30 12:50:49', 'Per prenotazioni scrivere una mail a countryside@laquacollection.it oppure telefonare al 003908119460050, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(34, 'Laqua Countryside – Menù Degustazione Carpe Diem con bevande per Una persona', 5, 'Questo buono regalo è valido per Menù Degustazione Carpe Diem destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', 'Menù Degustazione Carpe Diem accompagnato da calice di aperitivo, degustazione vini, minerali e caffetteria.', 'Si accettano esclusivamente prenotazioni per il servizio del pranzo dal giovedì al lunedì, esclusi i giorni festivi.', 225, NULL, NULL, '2024-03-30 12:54:05', '2024-03-30 12:54:05', 'Per prenotazioni scrivere una mail a countryside@laquacollection.it oppure telefonare al 003908119460050, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(35, 'Laqua Countryside – Menù Degustazione Nonno Antonino per Una persona', 5, 'Questo buono regalo è valido per Menù Degustazione Nonno Antonino destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', 'Menù Degustazione Nonno Antonino (bevande non incluse)', 'Si accettano esclusivamente prenotazioni per il servizio del pranzo dal giovedì al lunedì, esclusi i giorni festivi.', 160, NULL, NULL, '2024-03-30 12:55:35', '2024-03-30 12:55:35', 'Per prenotazioni scrivere una mail a countryside@laquacollection.it oppure telefonare al 003908119460050, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(36, 'Laqua Countryside – Menù Degustazione Nonno Antonino con bevande per Una persona', 5, 'Questo buono regalo è valido per Menù Degustazione Nonno Antonino destinato a una persona al ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', 'Menù Degustazione Nonno Antonino accompagnato da calice di aperitivo, degustazione vini, minerali e caffetteria.', 'Si accettano esclusivamente prenotazioni per il servizio del pranzo dal giovedì al lunedì, esclusi i giorni festivi.', 275, NULL, NULL, '2024-03-30 12:56:49', '2024-03-30 12:56:49', 'Per prenotazioni scrivere una mail a countryside@laquacollection.it oppure telefonare al 003908119460050, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(37, 'Laqua Countryside – Soggiorno tra gusto e natura in settimana', 5, 'Questo buono regalo è valido per il soggiorno tra gusto e natura di una notte in settimana con cena nel ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', '- 1 notte in camera doppia\n- Colazione à la carte servita al ristorante\n- Una cena per due persone con menù degustazione Nonno Antonino di 5 portate (bevande non incluse)', 'Il buono regalo è utilizzabile esclusivamente il lunedì, il mercoledì o il giovedì, esclusi i giorni festivi e pre-festivi.', 549, NULL, NULL, '2024-03-30 13:04:07', '2024-03-30 13:04:07', 'Per prenotazioni scrivere una mail a countryside@laquacollection.it oppure telefonare al 003908119460050, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(38, 'Laqua Countryside – Soggiorno tra gusto e natura due notti week-end', 5, 'Questo buono regalo è valido per il soggiorno tra gusto e natura di due notti nel fine settimana con cena nel ristorante una stella Michelin dello Chef Antonino Cannavacciuolo', '- 2 notti, dal venerdì alla domenica, in camera doppia\n- Colazione à la carte servita al ristorante\n- Una cena per due persone con menù degustazione Nonno Antonino di 5 portate (bevande escluse)', 'Il buono regalo è utilizzabile esclusivamente dal venerdì alla domenica, esclusi i giorni festivi e pre-festivi.', 1059, NULL, NULL, '2024-03-30 13:05:33', '2024-03-30 13:05:33', 'Per prenotazioni scrivere una mail a countryside@laquacollection.it oppure telefonare al 003908119460050, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(39, 'Laqua by the Lake – Wellness & Cryo per Una persona', 4, 'Questo buono regalo è valido per un percorso benessere presso la nostra The Longevity Suite SPA destinato a una persona', '- 1 sessione rigenerante di Criosauna della durata di 3 minuti a -85° C\n- Trattamento Longevity viso su consiglio della nostra SPA Manager\n- Massaggio corpo Longevity Deep Rejuvenating Detox \n- Un omaggio firmato Longevity Suite', 'Si accettano prenotazioni esclusivamente dal lunedì al venerdì, esclusi i giorni festivi.', 340, NULL, NULL, '2024-03-30 13:12:43', '2024-03-30 13:13:03', 'Per prenotazioni scrivere una mail a lake@laquacollection.it oppure telefonare al 00390323212121, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(40, 'Laqua by the Lake – Benessere sul lago per Una persona', 4, 'Questo buono regalo è valido per un percorso benessere presso la nostra The Longevity Suite SPA destinato a una persona', '– 1 sessione di Criosauna della durata di 3 minuti a -85° C\n– Massaggio corpo Longevity Deep Rejuvenating Detox\n– Un omaggio firmato Longevity Suite', 'Si accettano prenotazioni esclusivamente dal lunedì al venerdì, esclusi i giorni festivi.', 210, NULL, NULL, '2024-03-30 13:13:57', '2024-03-30 13:13:57', 'Per prenotazioni scrivere una mail a lake@laquacollection.it oppure telefonare al 00390323212121, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(41, 'Laqua by the Lake – Pausa relax healthy and happy per Una persona', 4, 'Questo buono regalo è valido per un percorso benessere presso la nostra The Longevity Suite SPA seguito da un pranzo leggero al bistrot Cannavacciuolo by the Lake destinato a una persona', '- 1 sessione di Cryo Extreme Elixir – Criosauna Total Body + Massaggio Connettivale\n- 1 pranzo healthy presso il Bistrot Cannavacciuolo by the Lake con antipasto, secondo piatto, acqua e caffè', 'Si accettano prenotazioni esclusivamente nelle giornate di lunedì, martedì, giovedì e venerdì, esclusi giorni festivi.', 149, NULL, NULL, '2024-03-30 13:15:55', '2024-03-30 13:15:55', 'Per prenotazioni scrivere una mail a lake@laquacollection.it oppure telefonare al 00390323212121, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(42, 'Laqua by the Lake – Pranzo vista lago per Una persona', 4, 'Questo buono regalo è valido per Menù Degustazione Brezza destinato a una persona al bistrot Cannavacciuolo by the Lake.', 'Menù Degustazione Brezza (bevande non incluse)', 'Si accettano prenotazioni esclusivamente per il servizio del pranzo dal lunedì al venerdì esclusi il mercoledì e i giorni festivi.', 95, NULL, NULL, '2024-03-30 13:17:34', '2024-03-30 13:17:34', 'Per prenotazioni scrivere una mail a lake@laquacollection.it oppure telefonare al 00390323212121, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(43, 'Laqua by the Lake – Degustazione con abbinamento vini per Una persona', 4, 'Questo buono regalo è valido per Menù Degustazione Brezza destinato a una persona al bistrot Cannavacciuolo by the Lake.', 'Menù Degustazione Brezza con calice di aperitivo, abbinamento vini, minerali e caffetteria.', 'Si accettano prenotazioni esclusivamente per il servizio del pranzo dal lunedì al venerdì esclusi il mercoledì e i giorni festivi.', 160, NULL, NULL, '2024-03-30 13:19:21', '2024-03-30 13:19:21', 'Per prenotazioni scrivere una mail a lake@laquacollection.it oppure telefonare al 00390323212121, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(44, 'Laqua by the Lake – Soggiorno Io, te e il lago in settimana', 4, 'Questo buono regalo è valido per il soggiorno Io, te e il lago di una notte in settimana con cena nel bistrot Cannavacciuolo by the Lake', '- 1 notte in una delle nostre Deluxe Suite con meravigliosa vista lago\n- Colazione a buffet servita nel Bistrot Cannavacciuolo by the Lake\n- Una cena per due persone con menù degustazione Brezza (bevande non incluse)', 'Il buono regalo è utilizzabile esclusivamente dal lunedì il giovedì, ad esclusione del mercoledì, dei giorni festivi e pre-festivi.', 729, NULL, NULL, '2024-03-30 13:22:57', '2024-03-30 13:22:57', 'Per prenotazioni scrivere una mail a lake@laquacollection.it oppure telefonare al 00390323212121, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.'),
(45, 'Laqua by the Lake – Soggiorno Io, te e il lago fine settimana', 4, 'Questo buono regalo è valido per il soggiorno Io, te e il lago di una notte nel fine settimana con cena nel bistrot Cannavacciuolo by the Lake', '- 1 notte in una delle nostre Deluxe Suite con meravigliosa vista lago\n- Colazione a buffet servita nel Bistrot Cannavacciuolo by the Lake\n- Una cena per due persone con menù degustazione Brezza (bevande non incluse)', 'Il buono regalo è utilizzabile esclusivamente dal venerdì alla domenica, esclusi i giorni festivi e pre-festivi.', 1549, NULL, NULL, '2024-03-30 13:24:35', '2024-03-30 13:24:35', 'Per prenotazioni scrivere una mail a lake@laquacollection.it oppure telefonare al 00390323212121, indicando il possesso del buono. Eventuali extra non inclusi nella dicitura sono da saldare in loco.');

--
-- Indici per le tabelle scaricate
--

--
-- Indici per le tabelle `activities`
--
ALTER TABLE `activities`
  ADD PRIMARY KEY (`id`),
  ADD KEY `activities_location_id_foreign` (`location_id`);

--
-- AUTO_INCREMENT per le tabelle scaricate
--

--
-- AUTO_INCREMENT per la tabella `activities`
--
ALTER TABLE `activities`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=46;

--
-- Limiti per le tabelle scaricate
--

--
-- Limiti per la tabella `activities`
--
ALTER TABLE `activities`
  ADD CONSTRAINT `activities_location_id_foreign` FOREIGN KEY (`location_id`) REFERENCES `locations` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
